# -*- coding: utf-8 -*-
"""DERİN_ÖĞRENME_VE_HİBRİT_YÖNTEMLER_İLE_CİLT_KANSERİ_SINIFLANDIRILMASI_VE_PERFORMANS_ANALİZİ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zy0DzeHynxXhbEmuYu0JqSqySmgPZvF9
"""

import os

# Bilgisayara dosya indirmeden, doğrudan Kaggle bilgilerini buraya gir
os.environ['KAGGLE_USERNAME'] = "yankyank"
os.environ['KAGGLE_KEY'] = "26703861"

# Kaggle kütüphanesini kur ve izinleri ayarla
!mkdir -p ~/.kaggle
with open(os.path.expanduser('~/.kaggle/kaggle.json'), 'w') as f:
    f.write(f'{ {"username":"{os.environ["KAGGLE_USERNAME"]}","key":"{os.environ["KAGGLE_KEY"]}"}}')
!chmod 600 ~/.kaggle/kaggle.json

# Eski yarım kalan indirmeler varsa temizle
!rm -f skin-cancer-mnist-ham10000.zip
!rm -rf /content/ham10000_dataset

# Veri setini Kaggle'dan indirme komutu
!kaggle datasets download -d kmader/skin-cancer-mnist-ham10000

# ZIP dosyasını klasöre çıkartma
!unzip -q skin-cancer-mnist-ham10000.zip -d /content/ham10000_dataset

import pandas as pd
import os
import glob
from sklearn.model_selection import train_test_split

# Klasör yolu tanımla
base_dir = '/content/ham10000_dataset'
metadata_path = os.path.join(base_dir, 'HAM10000_metadata.csv')

# Metadata dosyasını okuyalım
df = pd.read_csv(metadata_path)

# İki ayrı klasördeki tüm .jpg resimlerin yollarını topla
image_path_dict = {os.path.splitext(os.path.basename(x))[0]: x
                   for x in glob.glob(os.path.join(base_dir, '*', '*.jpg'))}

# Resim ID'lerine göre tam yolları dataframe'e ekle
df['image_path'] = df['image_id'].map(image_path_dict)

# Kanser türlerinin kısaltmalarını tam isimleriyle eşleşti
lesion_type_dict = {
    'nv': 'Melanocytic nevi',
    'mel': 'Melanoma',
    'bcc': 'Basal cell carcinoma',
    'akiec': 'Actinic keratoses',
    'vasc': 'Vascular lesions',
    'df': 'Dermatofibroma',
    'bkl': 'Benign keratosis',
}
df['cell_type'] = df['dx'].map(lesion_type_dict)

# Sınıf isimlerini bilgisayarın anlayacağı sayılara (0-6) dönüştürme
df['label'] = df['dx'].astype('category').cat.codes

print("--- VERİ SETİ SINIF DAĞILIMI ---")
print(df['cell_type'].value_counts())
print("\nToplam Görüntü Sayısı:", len(df))

# Veriyi %80 Eğitim ve %20 Test böl
train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df['label'])

# Kalan %20 yi yarı yarıya (%10 Val, %10 Test) paylaştırma
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42, stratify=temp_df['label'])

print(f"Eğitim Seti Boyutu: {len(train_df)}")
print(f"Doğrulama (Val) Seti Boyutu: {len(val_df)}")
print(f"Test Seti Boyutu: {len(test_df)}")

import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

# Giriş boyutunu belirliyoruz
IMG_SIZE = 224 # ideak buymuş

# Eğitim seti için Veri Artırımı (Data Augmentation) içeren transformasyonlar
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)), # Görüntüyü yeniden boyutlandır
    transforms.RandomHorizontalFlip(p=0.5), # Rastgele yatay çevirme
    transforms.RandomVerticalFlip(p=0.5),   # Rastgele dikey çevirme
    transforms.RandomRotation(degrees=20),   # Rastgele 20 dereceye kadar döndürme
    transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1), # Hafif renk/ışık değişimi
    transforms.ToTensor(), # Görseli PyTorch Tensörüne çevirir
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # ImageNet standart normalizasyonu
])

# Doğrulama ve Test setleri için sadece boyutlandırma ve normalizasyon
val_test_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Klasik HAM10000 PyTorch Sınıfı
class HAM10000Dataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.df = dataframe
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        # Resmin bilgisayardaki tam yolunu aldım
        img_path = self.df.iloc[idx]['image_path']
        # Resmi RGB formatında açtım
        image = Image.open(img_path).convert('RGB')
        # Etiket bilgisini alma
        label = int(self.df.iloc[idx]['label'])

        if self.transform:
            image = self.transform(image)

        return image, label

# Dataset nesnelerini oluşturma
train_dataset = HAM10000Dataset(train_df, transform=train_transform)
val_dataset = HAM10000Dataset(val_df, transform=val_test_transform)
test_dataset = HAM10000Dataset(test_df, transform=val_test_transform)

# Modellerin veriyi parça parça (Batch) işlemesini sağlayan DataLoader yapısı
BATCH_SIZE = 32 # benim pc için olması gereken buymuş chat dedi

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print(f"DataLoader'lar hazır! Eğitim için toplam {len(train_loader)} batch oluşturuldu.")

# DataLoader'ın düzgün çalışıp çalışmadığını test ett
try:
    images, labels = next(iter(train_loader))
    print("DataLoader sorunsuz çalışıyor!")
    print(f"Görüntü paket boyutu (Batch Shape): {images.shape}")
    print(f"Etiket paket boyutu (Label Shape): {labels.shape}")
except Exception as e:
    print("[HATA] Veri yüklenirken bir sorun oluştu. Hata mesajı:")
    print(e)

import torch
import torch.nn as nn
import torchvision.models as models
import time

# GPU Kontrolü
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Modelin eğitileceği cihaz: {device}")

# ResNet50 Modelini Ön Eğitimli Olarak Yükleme
resnet50 = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)

# Son katmanı 7 sınıfa göre güncelle
num_features = resnet50.fc.in_features
resnet50.fc = nn.Linear(num_features, 7)

# Modeli GPU belleğine taşı
resnet50 = resnet50.to(device)

# Kayıp Fonksiyonu ve Optimizer Tanımlama
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(resnet50.parameters(), lr=1e-4) # Medikal transfer öğrenme için ideal learning rate

# Eğitim Döngüsü Parameteresi
EPOCHS = 15
history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

for epoch in range(EPOCHS):
    start_time = time.time()

    # Eğitim
    resnet50.train()
    train_loss, train_corrects = 0.0, 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad() # Gradymantları sıfırla
        outputs = resnet50(images) # İleri besleme
        loss = criterion(outputs, labels) # Kayıp hesapla

        loss.backward() # Geriye yayılım
        optimizer.step() # Ağırlıkları güncelle

        _, preds = torch.max(outputs, 1)
        train_loss += loss.item() * images.size(0)
        train_corrects += torch.sum(preds == labels.data)

    epoch_train_loss = train_loss / len(train_loader.dataset)
    epoch_train_acc = train_corrects.double() / len(train_loader.dataset)

    # Doğrulama
    resnet50.eval()
    val_loss, val_corrects = 0.0, 0

    with torch.no_grad(): # Eğitimi durdur, hafızayı rahatlat
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = resnet50(images)
            loss = criterion(outputs, labels)

            _, preds = torch.max(outputs, 1)
            val_loss += loss.item() * images.size(0)
            val_corrects += torch.sum(preds == labels.data)

    epoch_val_loss = val_loss / len(val_loader.dataset)
    epoch_val_acc = val_corrects.double() / len(val_loader.dataset)

    # Geçmişi kaydet
    history['train_loss'].append(epoch_train_loss)
    history['train_acc'].append(epoch_train_acc.item())
    history['val_loss'].append(epoch_val_loss)
    history['val_acc'].append(epoch_val_acc.item())

    epoch_mins, epoch_secs = divmod(time.time() - start_time, 60)
    print(f"Epoch {epoch+1}/{EPOCHS} [{int(epoch_mins)}m {int(epoch_secs)}s] -> "
          f"Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.4f} || "
          f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.4f}")

# Kaybederşm falan diye kaydettim
torch.save(resnet50.state_dict(), 'resnet50_ham10000.pth')
print("ResNet50 model ağırlıkları 'resnet50_ham10000.pth' olarak başarıyla kaydedildi!")

import torch
import torch.nn as nn
import torchvision.models as models
import time

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Ön Eğitimli EfficientNet-B0 Modelini Yükleme
efficientnet_b0 = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)

# EfficientNet'in son katmanını 7 sınıfa çıktı verecek şekilde güncelle
num_features = efficientnet_b0.classifier[1].in_features
efficientnet_b0.classifier[1] = nn.Linear(num_features, 7)

# Modeli GPU belleğine taşı
efficientnet_b0 = efficientnet_b0.to(device)

# Kayıp Fonksiyonu ve Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(efficientnet_b0.parameters(), lr=1e-4)

# Eğitim değerleir
eff_history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

EPOCHS = 15

for epoch in range(EPOCHS):
    start_time = time.time()

    # Eğitim
    efficientnet_b0.train()
    train_loss, train_corrects = 0.0, 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = efficientnet_b0(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_loss += loss.item() * images.size(0)
        train_corrects += torch.sum(preds == labels.data)

    epoch_train_loss = train_loss / len(train_loader.dataset)
    epoch_train_acc = train_corrects.double() / len(train_loader.dataset)

    # Doğrulama
    efficientnet_b0.eval()
    val_loss, val_corrects = 0.0, 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = efficientnet_b0(images)
            loss = criterion(outputs, labels)

            _, preds = torch.max(outputs, 1)
            val_loss += loss.item() * images.size(0)
            val_corrects += torch.sum(preds == labels.data)

    epoch_val_loss = val_loss / len(val_loader.dataset)
    epoch_val_acc = val_corrects.double() / len(val_loader.dataset)

    # Geçmişi kaydet
    eff_history['train_loss'].append(epoch_train_loss)
    eff_history['train_acc'].append(epoch_train_acc.item())
    eff_history['val_loss'].append(epoch_val_loss)
    eff_history['val_acc'].append(epoch_val_acc.item())

    epoch_mins, epoch_secs = divmod(time.time() - start_time, 60)
    print(f"Epoch {epoch+1}/{EPOCHS} [{int(epoch_mins)}m {int(epoch_secs)}s] -> "
          f"Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.4f} || "
          f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.4f}")

# kayıt önemli
torch.save(efficientnet_b0.state_dict(), 'efficientnet_b0_ham10000.pth')
print("EfficientNet-B0 model ağırlıkları 'efficientnet_b0_ham10000.pth' olarak başarıyla kaydedildi!")

import numpy as np
import copy
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


# Eğittiğimiz EfficientNet modelinin bir kopyasını alıp classifier katmanını söktüm
feature_extractor = copy.deepcopy(efficientnet_b0)
feature_extractor.classifier = nn.Identity() # Classifier yerine Identity koyarak sadece ham özellikleri aldım
feature_extractor.eval() # Gradyan takibini kapattım

# Verileri ve Etiketleri Toplamafonksiyonu
def extract_features(data_loader):
    features_list = []
    labels_list = []

    with torch.no_grad():
        for images, labels in data_loader:
            images = images.to(device)
            # Resimleri modelden geçirip vektörleri al
            feats = feature_extractor(images)

            # Verileri CPU'ya ve Numpy formatına çevir
            features_list.append(feats.cpu().numpy())
            labels_list.append(labels.numpy())

    # Tüm paketleri tek bir büyük matrise dönüştür
    return np.concatenate(features_list, axis=0), np.concatenate(labels_list, axis=0)

#Eğitim setinin derin özellikleri çıkart
X_train, y_train = extract_features(train_loader)

#Validation setinin derin özellikleri çıkart
X_val, y_val = extract_features(val_loader)

print(f"Eğitim Özellik Matrisi Boyutu: {X_train.shape}")
print(f"Doğrulama Özellik Matrisi Boyutu: {X_val.shape}")

# SVM (Destek Vektör Makinesi) Modelinin Eğitilmesi

# Medikal çalışmalarda en popüler olan RBF çekirdekli SVM yapısını kurma
svm_model = SVC(kernel='rbf', C=1.0, random_state=42)

start_svm_time = time.time()
svm_model.fit(X_train, y_train)
svm_time = time.time() - start_svm_time

print(f"SVM Eğitimi [{int(svm_time // 60)}m {int(svm_time % 60)}s] içinde tamamlandı!")

# Doğruluk Değerleri Ölçümü
y_train_pred = svm_model.predict(X_train)
y_val_pred = svm_model.predict(X_val)

svm_train_acc = accuracy_score(y_train, y_train_pred)
svm_val_acc = accuracy_score(y_val, y_val_pred)

print(f"\nHibrit Model (EfficientNet + SVM) Sonuçları:")
print(f"-> Train Accuracy: {svm_train_acc:.4f}")
print(f"-> Validation Accuracy: {svm_val_acc:.4f}")

#kayıtttt
import joblib
joblib.dump(svm_model, 'efficientnet_svm_ham10000.pkl')
print("Hibrit SVM modeli 'efficientnet_svm_ham10000.pkl' olarak başarıyla kaydedildi!")

import torch
import torch.nn as nn
import torchvision.models as models
import time

# Ön Eğitimli Vision Transformer (ViT-B/16) Modelini Yükleme
vit_model = models.vit_b_16(weights=models.ViT_B_16_Weights.DEFAULT)

# ViT mimarisinin sınıflandırma kafasını 7 sınıfa çıktı verecek şekilde güncelleme
num_features = vit_model.heads.head.in_features
vit_model.heads.head = nn.Linear(num_features, 7)

# Modeli GPU belleğine taşı
vit_model = vit_model.to(device)

# Kayıp Fonksiyonu ve Optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(vit_model.parameters(), lr=1e-4)

# Eğitim değerleri
vit_history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

EPOCHS = 15

for epoch in range(EPOCHS):
    start_time = time.time()

    # Eğitim
    vit_model.train()
    train_loss, train_corrects = 0.0, 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = vit_model(images)
        loss = criterion(outputs, labels)

        loss.backward()
        optimizer.step()

        _, preds = torch.max(outputs, 1)
        train_loss += loss.item() * images.size(0)
        train_corrects += torch.sum(preds == labels.data)

    epoch_train_loss = train_loss / len(train_loader.dataset)
    epoch_train_acc = train_corrects.double() / len(train_loader.dataset)

    # Doğrulama
    vit_model.eval()
    val_loss, val_corrects = 0.0, 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = vit_model(images)
            loss = criterion(outputs, labels)

            _, preds = torch.max(outputs, 1)
            val_loss += loss.item() * images.size(0)
            val_corrects += torch.sum(preds == labels.data)

    epoch_val_loss = val_loss / len(val_loader.dataset)
    epoch_val_acc = val_corrects.double() / len(val_loader.dataset)

    # Geçmişi kaydet
    vit_history['train_loss'].append(epoch_train_loss)
    vit_history['train_acc'].append(epoch_train_acc.item())
    vit_history['val_loss'].append(epoch_val_loss)
    vit_history['val_acc'].append(epoch_val_acc.item())

    epoch_mins, epoch_secs = divmod(time.time() - start_time, 60)
    print(f"Epoch {epoch+1}/{EPOCHS} [{int(epoch_mins)}m {int(epoch_secs)}s] -> "
          f"Train Loss: {epoch_train_loss:.4f} | Train Acc: {epoch_train_acc:.4f} || "
          f"Val Loss: {epoch_val_loss:.4f} | Val Acc: {epoch_val_acc:.4f}")

#kayıtt
torch.save(vit_model.state_dict(), 'vit_model_ham10000.pth')
print("Vision Transformer model ağırlıkları 'vit_model_ham10000.pth' olarak başarıyla kaydedildi!")

import torch
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# Metrikleri saklamak için bir dizi/fonsk
final_results = {}

# Test fonksiyonu
def evaluate_pytorch_model(model, name):
    model.eval()
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())

    acc = accuracy_score(all_labels, all_preds)
    prec, rec, f1, _ = precision_recall_fscore_support(all_labels, all_preds, average='macro')

    final_results[name] = [acc*100, prec*100, rec*100, f1*100]

# ResNet50 Test Et
evaluate_pytorch_model(resnet50, "Model 1: ResNet50")

# EfficientNet-B0 Test Et
evaluate_pytorch_model(efficientnet_b0, "Model 2: EfficientNet-B0")

# Vision Transformer Test Et
evaluate_pytorch_model(vit_model, "Model 4: Vision Transformer (ViT)")

# Hibrit Model (EfficientNet + SVM) Test Et

# SVM için önce test setinin derin özelliklerini çıkart
feature_extractor.eval()
X_test_list, y_test_list = [], []
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        feats = feature_extractor(images)
        X_test_list.append(feats.cpu().numpy())
        y_test_list.append(labels.numpy())

X_test = np.concatenate(X_test_list, axis=0)
y_test = np.concatenate(y_test_list, axis=0)

# SVM tahmini yap
y_test_pred = svm_model.predict(X_test)
svm_acc = accuracy_score(y_test, y_test_pred)
svm_prec, svm_rec, svm_f1, _ = precision_recall_fscore_support(y_test, y_test_pred, average='macro')

final_results["Model 3: EfficientNet + SVM (Hibrit)"] = [svm_acc*100, svm_prec*100, svm_rec*100, svm_f1*100]

# tablo
print("\n TEST METRİKLERİ KARŞILAŞTIRMA TABLOSU")
df_results = pd.DataFrame.from_dict(
    final_results,
    orient='index',
    columns=['Accuracy (%)', 'Precision (%)', 'Recall (%)', 'F1-Score (%)']
)
# Sonuçları virgülden sonra 2 basamak olacak şekilde formatla
print(df_results.round(2))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# HAM10000 sınıf isimlerini alfabetik sırayla tanımlayalım
class_names = ['akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc']

print("CONFUSION MATRIX")

# Pytorch modellerinden tahminleri toplama fonksiyonu
def get_all_preds(model):
    model.eval()
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            outputs = model(images)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_preds)

# Tahminleri topla
y_true_res, y_pred_res = get_all_preds(resnet50)
y_true_eff, y_pred_eff = get_all_preds(efficientnet_b0)
y_true_vit, y_pred_vit = get_all_preds(vit_model)

# Hibrit modelin (SVM) tahminleri zaten bir önceki adımda 'y_test_pred' ve 'y_test' olarak elimizde vardı

# Grafik Alanını Oluşturma
fig, axes = plt.subplots(2, 2, figsize=(16, 14))
fig.suptitle('HAM10000 Test Seti - Karmaşıklık Matrisleri (Confusion Matrices)', fontsize=18, fontweight='bold', y=0.95)

# Çizim ayarları için yardımcı liste
models_cm_data = [
    {"title": "Model 1: ResNet50", "true": y_true_res, "pred": y_pred_res, "ax": axes[0, 0]},
    {"title": "Model 2: EfficientNet-B0", "true": y_true_eff, "pred": y_pred_eff, "ax": axes[0, 1]},
    {"title": "Model 3: EfficientNet + SVM (Hibrit)", "true": y_test, "pred": y_test_pred, "ax": axes[1, 0]},
    {"title": "Model 4: Vision Transformer (ViT)", "true": y_true_vit, "pred": y_pred_vit, "ax": axes[1, 1]}
]

# Her bir modeli matrise dökme
for m in models_cm_data:
    cm = confusion_matrix(m["true"], m["pred"])

    # Seaborn ile ısı haritası çizimi
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=m["ax"], cbar=False,
                xticklabels=class_names, yticklabels=class_names,
                annot_kws={"size": 12, "weight": "bold"})

    m["ax"].set_title(m["title"], fontsize=14, fontweight='bold', pad=10)
    m["ax"].set_xlabel('Tahmin Edilen Sınıf', fontsize=11)
    m["ax"].set_ylabel('Gerçek Sınıf', fontsize=11)

# Grafik yerleşimini sıkılaştır
plt.tight_layout(rect=[0, 0.03, 1, 0.92])

# Görseli Yüksek Kalitede Diske Kaydetme
plt.savefig('ham10000_confusion_matrices.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

# ResNet50 eğitim verileri
resnet_history = {
    'train_loss': [0.7683, 0.4857, 0.3909, 0.3301, 0.2783],
    'train_acc': [0.7320, 0.8271, 0.8605, 0.8794, 0.8982],
    'val_loss': [0.5860, 0.4326, 0.3926, 0.3819, 0.3673],
    'val_acc': [0.7882, 0.8492, 0.8631, 0.8651, 0.8661]
}

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
epochs = range(1, len(eff_history['train_loss']) + 1)

# Kayıp (Loss) Grafiği
axes[0].plot(epochs, resnet_history['train_loss'], label='Eğitim Kaybı', marker='o', color='blue')
axes[0].plot(epochs, resnet_history['val_loss'], label='Doğrulama Kaybı', marker='s', color='red')
axes[0].set_title('ResNet50 Loss (Kayıp) Eğrisi', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].set_xticks(epochs)
axes[0].grid(True, linestyle='--', alpha=0.7)
axes[0].legend()

# Başarım Grafiği
axes[1].plot(epochs, resnet_history['train_acc'], label='Eğitim Başarısı', marker='o', color='green')
axes[1].plot(epochs, resnet_history['val_acc'], label='Doğrulama Başarısı', marker='s', color='orange')
axes[1].set_title('ResNet50 Accuracy (Başarım) Eğrisi', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Accuracy', fontsize=12)
axes[1].set_xticks(epochs)
axes[1].grid(True, linestyle='--', alpha=0.7)
axes[1].legend()

plt.tight_layout()
plt.savefig('resnet50_loss_grafigi.png', dpi=300, bbox_inches='tight')
plt.show()

# EFFICIENTNET-B0 LOSS VE ACCURACY GRAFİKLERİ

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
epochs = range(1, len(eff_history['train_loss']) + 1)

# Kayıp (Loss) Grafiği
axes[0].plot(epochs, eff_history['train_loss'], label='Eğitim Kaybı', marker='o', color='blue')
axes[0].plot(epochs, eff_history['val_loss'], label='Doğrulama Kaybı', marker='s', color='red')
axes[0].set_title('EfficientNet-B0 Loss (Kayıp) Eğrisi', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].set_xticks(epochs)
axes[0].grid(True, linestyle='--', alpha=0.7)
axes[0].legend()

# Başarım (Accuracy) Grafiği
axes[1].plot(epochs, eff_history['train_acc'], label='Eğitim Başarısı', marker='o', color='green')
axes[1].plot(epochs, eff_history['val_acc'], label='Doğrulama Başarısı', marker='s', color='orange')
axes[1].set_title('EfficientNet-B0 Accuracy (Başarım) Eğrisi', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Accuracy', fontsize=12)
axes[1].set_xticks(epochs)
axes[1].grid(True, linestyle='--', alpha=0.7)
axes[1].legend()

plt.tight_layout()
plt.savefig('efficientnet_loss_grafigi.png', dpi=300, bbox_inches='tight')
plt.show()

# VISION TRANSFORMER (ViT) LOSS VE ACCURACY

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
epochs = range(1, len(vit_history['train_loss']) + 1)

# Kayıp (Loss) Grafiği
axes[0].plot(epochs, vit_history['train_loss'], label='Eğitim Kaybı', marker='o', color='blue')
axes[0].plot(epochs, vit_history['val_loss'], label='Doğrulama Kaybı', marker='s', color='red')
axes[0].set_title('ViT Loss (Kayıp) Eğrisi', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].set_xticks(epochs)
axes[0].grid(True, linestyle='--', alpha=0.7)
axes[0].legend()

# Başarım Grafiği
axes[1].plot(epochs, vit_history['train_acc'], label='Eğitim Başarısı', marker='o', color='green')
axes[1].plot(epochs, vit_history['val_acc'], label='Doğrulama Başarısı', marker='s', color='orange')
axes[1].set_title('ViT Accuracy (Başarım) Eğrisi', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Accuracy', fontsize=12)
axes[1].set_xticks(epochs)
axes[1].grid(True, linestyle='--', alpha=0.7)
axes[1].legend()

plt.tight_layout()
plt.savefig('vit_loss_grafigi.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
epochs = range(1, len(history['train_loss']) + 1)

# renk
color_res = '#1f77b4' # Mavi (ResNet50)
color_eff = '#2ca02c' # Yeşil (EfficientNet-B0)
color_vit = '#d62728' # Kırmızı (ViT)

# 1. KAYIP (LOSS) GRAFİĞİ

axes[0].plot(epochs, history['train_loss'], linestyle='--', color=color_res, alpha=0.5, label='ResNet50 (Train)')
axes[0].plot(epochs, eff_history['train_loss'], linestyle='--', color=color_eff, alpha=0.5, label='EfficientNet-B0 (Train)')
axes[0].plot(epochs, vit_history['train_loss'], linestyle='--', color=color_vit, alpha=0.5, label='ViT (Train)')

axes[0].plot(epochs, history['val_loss'], marker='o', color=color_res, linewidth=2, label='ResNet50 (Val)')
axes[0].plot(epochs, eff_history['val_loss'], marker='s', color=color_eff, linewidth=2, label='EfficientNet-B0 (Val)')
axes[0].plot(epochs, vit_history['val_loss'], marker='^', color=color_vit, linewidth=2, label='ViT (Val)')

axes[0].set_title('Modellerin Loss (Kayıp) Karşılaştırması', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch (Tur)', fontsize=12)
axes[0].set_ylabel('Loss (Kayıp)', fontsize=12)
axes[0].set_xticks(epochs)
axes[0].grid(True, linestyle='--', alpha=0.7)
axes[0].legend(fontsize=10)

# 2. BAŞARIM (ACCURACY) GRAFİĞİ

axes[1].plot(epochs, history['train_acc'], linestyle='--', color=color_res, alpha=0.5, label='ResNet50 (Train)')
axes[1].plot(epochs, eff_history['train_acc'], linestyle='--', color=color_eff, alpha=0.5, label='EfficientNet-B0 (Train)')
axes[1].plot(epochs, vit_history['train_acc'], linestyle='--', color=color_vit, alpha=0.5, label='ViT (Train)')

axes[1].plot(epochs, history['val_acc'], marker='o', color=color_res, linewidth=2, label='ResNet50 (Val)')
axes[1].plot(epochs, eff_history['val_acc'], marker='s', color=color_eff, linewidth=2, label='EfficientNet-B0 (Val)')
axes[1].plot(epochs, vit_history['val_acc'], marker='^', color=color_vit, linewidth=2, label='ViT (Val)')

axes[1].set_title('Modellerin Accuracy (Başarım) Karşılaştırması', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch (Tur)', fontsize=12)
axes[1].set_ylabel('Accuracy (Doğruluk)', fontsize=12)
axes[1].set_xticks(epochs)
axes[1].grid(True, linestyle='--', alpha=0.7)
axes[1].legend(fontsize=10)

plt.tight_layout()
plt.savefig('tum_modeller_karsilastirma.png', dpi=300, bbox_inches='tight')
plt.show()